augmentation:
  train:
    -
      name: randomresize2
      base_size: [128, 128]         
      random_range: [0.5, 1.4]    
      interpolation: bilinear
    -
      name: randomhorizontalflip
      p: 0.5
    - 
      name: posetopdownaffine
      scale: [0.8, 1.3]
      scale_prob: 1.
      translate: 0.2
      translate_prob: 1.
      rotation: 60
      rotation_prob: 1.
      size: [256, 256]
    -
      name: colorjitter
      brightness: 0.1
      contrast: 0.4
      saturation: 0.3
      hue: 0.05
      p: 0.5
    -
      name: totensor
      pixel_range: 1.0
    -
      name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    -
      name: mixing
      mixup: [0.2,1.0]
      cutmix: [1.0,1.0]
      inplace: false

  inference:
    - 
      name: posetopdownaffine
      scale: [1., 1.]
      scale_prob: 0.
      translate: 0.
      translate_prob: 0.
      rotation: 0
      rotation_prob: 0.
      size: [256, 256]
    -
      name: totensor
      pixel_range: 1.0
    -
      name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]